version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    command: sh -c "npm run dev"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"
    networks:
      - backend
    depends_on:
      - db
  db:
    build:
      context: ./database/mysql
      dockerfile: Dockerfile
    env_file:
      - .env
    tty: true
    stdin_open: true
    volumes:
      - db_data:/var/lib/mysql
      - ./database/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - backend

volumes:
  node_modules:

  db_data:

networks:
  backend:
    driver: bridge
